const sampleData = {
  products: [
    {
      name: 'Fender American Professional II Stratocaster',
      slug: 'fender-american-professional-ii-stratocaster',
      category: 'Electric Guitars',
      description: 'Iconic tone and versatile playability for professionals',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 1699.99,
      brand: 'Fender',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Gibson Les Paul Standard 60s',
      slug: 'gibson-les-paul-standard-60s',
      category: 'Electric Guitars',
      description: 'Legendary sustain and warmth with vintage appeal',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 2499.0,
      brand: 'Gibson',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'PRS SE Custom 24',
      slug: 'prs-se-custom-24',
      category: 'Electric Guitars',
      description: 'Signature style and versatility at a great value',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 899.0,
      brand: 'PRS',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Ibanez RG450DXB',
      slug: 'ibanez-rg450dxb',
      category: 'Electric Guitars',
      description: 'Sleek design and fast neck ideal for shredders',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 499.99,
      brand: 'Ibanez',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Yamaha FG830 Acoustic Guitar',
      slug: 'yamaha-fg830-acoustic-guitar',
      category: 'Acoustic Guitars',
      description: 'Rich sound and great build quality for all levels',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 349.99,
      brand: 'Yamaha',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Taylor GS Mini Mahogany',
      slug: 'taylor-gs-mini-mahogany',
      category: 'Acoustic Guitars',
      description: 'Compact body with big sound — ideal for travel',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 599.0,
      brand: 'Taylor',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
